name: "web_app"
mode: "dev"
port: 8081
version: "v0.1.3"
start_time: "2020-01-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50


redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100